repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        name: isort
        language_version: python3.12
        additional_dependencies: []

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        name: black
        language_version: python3.12
        additional_dependencies: []
