[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = "--disable-warnings --maxfail=1"

[tool.pyright]
typeCheckingMode = "off"
venvPath = "/opt/homebrew/Caskroom/miniforge/base/envs"
venv = "py312"

[tool.isort]
profile = "black"